# Site-wide settings

title: "The Explainer's Press"
tagline: "Chapbooks of South African poetry"
description: "Affordable chapbooks of English poems and translations into English by South Africans, bringing new poetry and writers to the attention of a wider audience."
image: "explainers.jpg"
url: "https://theexplainerspress.co.za"
